package ALLMAINFILES;

import NgoLoginAndRegister.LoginAndRegister;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import javax.swing.JOptionPane;
import swing.EventLogin;

public class NgoLogin extends javax.swing.JFrame {

    public NgoLogin() {
        initComponents();
       
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\krishna\\Desktop\\KIIT\\UpdatedBloodBuddies\\src\\ALLMAINFILES\\blood-donation.png");
        this.setIconImage(icon);
        
        setBounds(-6, -6, 1600, 900);

        EventLogin event = new EventLogin() {
            @Override
            public void loginDone() {
                System.out.println("LOgin done ");
            }

            @Override
            public void logOut() {

                System.out.println("Logout ");
            }
        };
        Socket sock = new Socket();
        InetSocketAddress addr = new InetSocketAddress("www.google.com", 80);
        try {
            sock.connect(addr, 3000);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Please connect to Internet,Otherwise data won't get updated on any page!");
        } finally {
            try {
                sock.close();
            } catch (IOException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAndRegister1 = new NgoLoginAndRegister.LoginAndRegister();
        loginAndRegister2 = new NgoLoginAndRegister.LoginAndRegister();
        panel1 = new java.awt.Panel();
        button1 = new swing.Button();

        loginAndRegister1.setBackground(new java.awt.Color(231, 233, 226));
        loginAndRegister1.setPreferredSize(new java.awt.Dimension(1600, 800));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOOD BANK MANAGEMENT SYSTEM");
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginAndRegister2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginAndRegister2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginAndRegister2MouseExited(evt);
            }
        });
        getContentPane().add(loginAndRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 810));

        panel1.setBackground(new java.awt.Color(255, 204, 204));

        button1.setBackground(new java.awt.Color(255, 51, 51));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Back ");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 180, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        dispose();        // TODO add your handling code here:
        new SelectionPage().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void loginAndRegister2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAndRegister2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAndRegister2MouseExited

    private void loginAndRegister2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAndRegister2MouseEntered
        // TODO add your handling code here:
        String stat = loginAndRegister2.l1.getText();
        System.out.println("Me" + stat);
        if ("Login".equals(stat)) {
            setVisible(false);
        }
    }//GEN-LAST:event_loginAndRegister2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NgoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NgoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NgoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NgoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NgoLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button1;
    private NgoLoginAndRegister.LoginAndRegister loginAndRegister1;
    private NgoLoginAndRegister.LoginAndRegister loginAndRegister2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
