package ALLMAINFILES;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import javax.swing.JOptionPane;

public class SelectionPage extends javax.swing.JFrame {

    public SelectionPage() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\krishna\\Desktop\\KIIT\\UpdatedBloodBuddies\\src\\ALLMAINFILES\\blood-donation.png");
        this.setIconImage(icon);
        setBounds(-6, -6, 1600, 900);
        Socket sock = new Socket();
        InetSocketAddress addr = new InetSocketAddress("www.google.com", 80);
        try {
            sock.connect(addr, 3000);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Please connect to Internet,Otherwise data won't get updated on any page!");
        } finally {
            try {
                sock.close();
            } catch (IOException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hospital = new javax.swing.JButton();
        NGO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOOD BANK MANAGEMENT SYSTEM");
        setAutoRequestFocus(false);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hospital.setBackground(new java.awt.Color(255, 255, 255));
        Hospital.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        Hospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALLMAINFILES/hospital.png"))); // NOI18N
        Hospital.setText("HOSPITAL");
        Hospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalActionPerformed(evt);
            }
        });
        getContentPane().add(Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 370, 320, 90));

        NGO.setBackground(new java.awt.Color(255, 255, 255));
        NGO.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        NGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALLMAINFILES/ngo.png"))); // NOI18N
        NGO.setText("NGO    ");
        NGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NGOActionPerformed(evt);
            }
        });
        getContentPane().add(NGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 280, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALLMAINFILES/Selectionbackground.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1600, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(1600, 900));
        jLabel1.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 1600, 1060));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NGOActionPerformed
        System.out.println("NGO Button Pressed Ok cool ");

       
        new NgoLogin().setVisible(true);
         setVisible(false);
        dispose();


    }//GEN-LAST:event_NGOActionPerformed

    private void HospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalActionPerformed

        System.out.println("Hospital  Button Pressed  ");
      
        new HospitalLogin().setVisible(true);
  setVisible(false);

    }//GEN-LAST:event_HospitalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hospital;
    private javax.swing.JButton NGO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
